from django.conf.urls import patterns, include, url
from views import *

urlpatterns = patterns('',
    url(r'^categorias/$', categorias, name='categorias'),
    url(r'^categoria/(?P<id_cat>\d+)/$', edit_categorias, name='edit_categorias'),
    url(r'^categorias/(?P<id_cat>\d+)/$', borrar_categoria, name='borrar_categoria'),
    url(r'^productos/$', productos, name='productos'),
    url(r'^productos/(?P<id_prod>\d+)/$', edit_productos, name='edit_productos'),
    url(r'^producto/(?P<id_prod>\d+)/$', borrar_producto, name='borrar_producto'),
    url(r'^ofertas/$', ofertas, name='ofertas'),
    url(r'^ofertas/prod/(?P<id_cat>\d+)/$', obtener_productos, name='obtener_productos'),
    url(r'^ofertas/(?P<id_oferta>\d+)/$', edit_ofertas, name='edit_ofertas'),
    url(r'^oferta/(?P<id_oferta>\d+)/$', borrar_oferta, name='borrar_oferta'),
    url(r'^producto/ver/(?P<id_prod>\d+)/$', ver_producto, name='ver_producto'),
    url(r'^micarrito/$', ver_carrito, name='ver_carrito'),
    url(r'^micarrito/remove/(?P<id_prod>\d+)/$', remove_from_cart, name='remove_from_cart'),
    url(r'^procesarpedido/$', procesar_pedido, name='procesar_pedido'),
    url(r'^procesarpedido/(?P<id_prod>\d+)/$', procesar_pedido_producto, name='procesar_pedido_producto'),
    url(r'^procesarpedido/confirmar/$', confirmar_pedido, name='confirmar_pedido'),
    url(r'^procesarpedido/cancelar/$', cancelar_pedido, name='cancelar_pedido'),
    url(r'^mispedidos/$', mis_pedidos, name='mis_pedidos'),
    url(r'^gestionpedidos/$', gestion_pedidos, name='gestion_pedidos'),
    url(r'^procesapedido/(?P<id_pedido>\d+)/$', procesa_pedido, name='procesa_pedido'),
    url(r'^procesapedido/anularitem/(?P<id_prodpedido>\d+)/$', anula_item, name='anula_item'),
    url(r'^procesapedido/facturar/(?P<id_pedido>\d+)/$', facturar_pedido, name='facturar_pedido'),
    url(r'^procesapedido/rechazar/(?P<id_pedido>\d+)/$', rechazar_pedido, name='rechazar_pedido'),
    url(r'^procesapedido/despachar/(?P<id_pedido>\d+)/$', despachar_pedido, name='despachar_pedido'),
    url(r'^procesapedido/registrarpago/(?P<id_pedido>\d+)/$', registrar_pago, name='registrar_pago'),
    url(r'^misfacturas/$', mis_facturas, name='mis_facturas'),
    url(r'^misfacturas/ver/(?P<id_factura>\d+)/$', ver_factura, name='ver_factura'),
	url(r'^ver/(?P<id_cat>\d+)/$', ver_categoria, name='ver_categoria'),
	url(r'^procesapedido/modificaitem/(?P<id_prodpedido>\d+)/$', modifica_item, name='modifica_item'),
)
